import { AppInitializer, ReduxProvider } from '@/providers'
import { Toaster } from 'react-hot-toast'
import '@/styles/globals.css'
import { InitialLoader, PageTransitionWrapper } from '@/components'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='vi' suppressHydrationWarning>
      <body
        className='bg-gray-50 text-gray-900 font-sans'
        suppressHydrationWarning
      >
        <Toaster />
        <ReduxProvider>
          <AppInitializer />
          <InitialLoader>
            <PageTransitionWrapper>{children}</PageTransitionWrapper>
          </InitialLoader>
        </ReduxProvider>
      </body>
    </html>
  )
}
